-- AlterTable: track a per-attempt idempotency key on payments so a retry
-- (issue #159) is a distinct attempt with a NEW key — the previous failed
-- attempt is never duplicated. The key is server-generated (uuid) at create
-- time and regenerated by the retry action.

ALTER TABLE "Payment" ADD COLUMN "idempotencyKey" TEXT;
